spring:
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackUri: forward:/departmentServiceFallBack
            - name: Retry
              args:
                  retries: 3
                  statuses: BAD_GATEWAY, GATEWAY_TIMEOUT

        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-SERVICE
                fallbackUri: forward:/employeeServiceFallBack
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT


server:
  port: 9191

logging:
 level:
   org.springframework.cloud.gateway: DEBUG
   org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: TRACE
   org.springframework.cloud.gateway.filter.factory.Retry: TRACE

