server:
  port: 8081

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:postgresql://departmentdb:5432/departmentdb    
    username: admin
    password: admin

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      

logging:
  level:
    de.meziane.ms.controller.DepartmentController: DEBUG
