server:
  port: 8081

spring:
  application:
    name: department-service
  datasource:
    url: jdbc:postgresql://departmentdb:5432/departmentdb    
    username: admin
    password: admin

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-registry:8761/eureka}
      

logging:
  level:
    de.meziane.ms.controller.DepartmentController: DEBUG
