server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://departmentdb:5432/departmentdb    
    username: admin
    password: admin

  jpa:
    defer-datasource-initialization: true
    how-sql: true
#  sql:
#    init:
#      mode: always
      
logging:
  level:
    de.meziane.ms.controller.EmployeeController: DEBUG
