server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://employeedb:5432/employeedb
    username: admin
    password: admin
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    de.meziane.ms.controller.EmployeeController: DEBUG
