server:
  port: 8082
spring:
  application:
    name: employee-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://employeedb:5432/employeedb
    username: admin
    password: admin
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-registry:8761/eureka}

logging:
  level:
    de.meziane.ms.controller.EmployeeController: DEBUG
