server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customerdb
    username: admin
    password: admin
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always

logging:
  level:
    de.meziane.ms.controller.EmployeeController: DEBUG
